/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 sci-fi_computer_room.glb 
Author: Michael V (https://sketchfab.com/bossdeff)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-computer-room-a149d5bfcef6496c9a0606b5ce5ebf27
Title: Sci-Fi Computer Room
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Room(props) {
  const { nodes, materials } = useGLTF('/models/sci-fi_computer_room.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.987}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Desk_1} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Posters} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Keyboard} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.speaker_2} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.BG_Dark} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Carpet} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Emission} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Emission_Blue} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Foam_Acoustic} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.Foam_Acoustic} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Trim_Sheet_Wall} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.Monitor_Single} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/sci-fi_computer_room.glb')
